In [20]:
import numpy as np

In [2]:
#!pip install numpy

In [4]:
a1 = np.array([1,2,3,4,5])
#리스트 사이에 , 가 없다면 ndarray 

print([1,2,3,4,5])
print(a1)
print(type(a1))

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
a2 = np.arange(10)
print(a2)

# 변수 a3, 100 아래 3의 배수
a3 = np.arange(3,100, 3)
print(a3)

# 1에서 부터 10아래 0.5씩 증가하는 숫자
a4 = np.arange(1.3,10,0.5)
print(a4)

#lista = [i for i in range(1.3, 10, 0.5)]

[0 1 2 3 4 5 6 7 8 9]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]
[1.3 1.8 2.3 2.8 3.3 3.8 4.3 4.8 5.3 5.8 6.3 6.8 7.3 7.8 8.3 8.8 9.3 9.8]


In [14]:
a4 = np.linspace(0, 10, 15) # 시작 끝 갯수(끝 숫자보다 크게 나눌수 있다.)
print(a4)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [21]:
a5 = np.zeros(5)
print(a5)

a6 = np.ones(5, dtype=np.int64)
print(a6)
$ a6.astype(np.float64)

[0. 0. 0. 0. 0.]
[1 1 1 1 1]


array([1., 1., 1., 1., 1.])

In [46]:
a10 = np.arange(10,100,5)
print(a10)

# 특정인덱스as
print(a10[10], a10[-1])
# 스타트, 스탑
print(a10[3:7])
# 스타트, 스탑, 스텝
print(a10[::2])
#1,3,7 인데스를 리스트에 담기
print(a10[[1,3,7]])

#list1 = [x for x in range(10,100,0.5)]
#print(list1)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
60 95
[25 30 35 40]
[10 20 30 40 50 60 70 80 90]
[15 25 45]


In [47]:
a10 = np.arange(10,100,5)
print(a10)
print(a10[a10%10 == 5])

# 브로드케스팅의 ndarray가 있기때문에
x = (a10%10 == 5)
print(x)
print(x.shape) #
print(a10.shape)
print(a10[x])

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 25 35 45 55 65 75 85 95]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True]
int32
(18,)
(18,)
[15 25 35 45 55 65 75 85 95]


In [16]:
lista = [1, 2,3.5, 4.2] 
a7 = np.array(lista)
    
print(a7)

listb = [1, 2 ,'abc','def'] # 데이터 타입을 통일
all = np.array(listb);
print(all)

print(all.dtype)
print(a7.dtype)
print(a7.ndim) # 몇 차원 배열인지?
print(a7.shape) # 모양을 어떻게 되는지? 1, 2차원 형태 투플로 shape을 준다
print(a7.size) # 1차원일때는 숫자랑 똑같음(배열안에 있는 엘리먼트의 개수)

# 잘 사용안함.
print(a7.itemsize) #몇 바이트?
print(a7.data) # 메모리 위치

[1.  2.  3.5 4.2]
['1' '2' 'abc' 'def']
<U11
float64
1
(4,)
4
8


In [64]:
lista = [x for x in range(5)]
listb = [x for x in range(10,15)]

print(lista)
print(listb)

print(lista + listb)
#print(lista - listb)
#print(lista * listb)
#print(lista / listb)

[0, 1, 2, 3, 4]
[10, 11, 12, 13, 14]
[0, 1, 2, 3, 4, 10, 11, 12, 13, 14]


In [60]:
a1 = np.arange(5)
a2 = np.arange(10,15)
print(a1)
print(a2)

# 인덱스 별로 덧셈
# 인덱스의 크기가 다르면 안됨(개수)
print('add:',a1+a2)
# 연결을 시키고 싶으면 튜플에 담아서 매개변수로 concatenate()에 줘야한다.
print(np.concatenate((a1,a2)))
print('sub:',a1-a2)
print('mul:',a1*a2)
print('div:',a1/a2)

[0 1 2 3 4]
[10 11 12 13 14]
add: [10 12 14 16 18]
[ 0  1  2  3  4 10 11 12 13 14]
sub: [-10 -10 -10 -10 -10]
mul: [ 0 11 24 39 56]
div: [0.         0.09090909 0.16666667 0.23076923 0.28571429]
