In [1]:
import requests
import numpy as np

x = requests.get('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [4]:
raw_data=[]
for line in x.text.split('\n'):
    raw_data.append(line.split(','))
    
for sample in raw_data:
    for i, value in enumerate(sample[:4]):
        try:
            sample[i] =float(value)
        except:
            sample[i] = 0.0

In [5]:
print(raw_data[:3])

[[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'], [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'], [4.7, 3.2, 1.3, 0.2, 'Iris-setosa']]


## 문자열 -> 숫자

-- Iris Setosa  --> 0

-- Iris Versicolour  --> 1

-- Iris Vigineica  --> 2

np_data - np.array(raw_data)


In [9]:
for sample in raw_data:
    if len(sample)< 2:
        continue
    if 'setosa' in  sample[-1]:
        sample[-1] = 0.0
    elif 'versicolor' in sample[-1]:
        sample[-1] = 1.0
    elif 'virginica' in sample[-1]:
        sample[-1] = 2.0     

In [10]:
print(raw_data[0])
print(raw_data[51])
print(raw_data[101])

[5.1, 3.5, 1.4, 0.2, 0.0]
[6.4, 3.2, 4.5, 1.5, 1.0]
[5.8, 2.7, 5.1, 1.9, 2.0]


In [11]:
print(raw_data[-3:])
print(len(raw_data))
raw_data = raw_data[:150]

[[5.9, 3.0, 5.1, 1.8, 2.0], [0.0], [0.0]]
152


In [12]:
print(len(raw_data))

150


In [14]:
np_data = np.array(raw_data)
np_data.shape
np_data[:3]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ]])

### 기본 통계 값

* 전체(150샘플) 평균, 표준편차 - sepal length, sepal width, petal length, petal width

* 품종별(50개씩) 평균, 표준편차

* 평균 np.mean()

* 표준편타 np.std()

In [51]:
np_mean = np.mean(np_data,axis=0)
print('sepal_length :{}, sepal_width: {}, petal_length : {}, petal_width: {}'.format(np_mean[0],np_mean[1],np_mean[2],np_mean[3]))
np_std = np.std(np_data,axis=0)
print('sepal_length :{}, sepal_width: {}, petal_length : {}, petal_width: {}'.format(np_std[0],np_std[1],np_std[2],np_std[3]))

sepal_length :5.843333333333335, sepal_width: 3.0540000000000007, petal_length : 3.7586666666666693, petal_width: 1.1986666666666672
sepal_length :0.8253012917851409, sepal_width: 0.4321465800705435, petal_length : 1.7585291834055201, petal_width: 0.760612618588172


In [57]:
print(np.corrcoef(np_data.T)) #상관도

[[ 1.         -0.10936925  0.87175416  0.81795363  0.78256123]
 [-0.10936925  1.         -0.4205161  -0.35654409 -0.4194462 ]
 [ 0.87175416 -0.4205161   1.          0.9627571   0.94904254]
 [ 0.81795363 -0.35654409  0.9627571   1.          0.95646382]
 [ 0.78256123 -0.4194462   0.94904254  0.95646382  1.        ]]


In [47]:
sepal_length_min = np.min(np_data[:,0])
print(sepal_length_min)
sepal_width_min = np.min(np_data[:,1])
print(sepal_width_min)
petal_length_min = np.min(np_data[:,2])
print(petal_length_min)
petal_width_min = np.min(np_data[:,3])
print(petal_width_min)

4.3
2.0
1.0
0.1


In [48]:
sepal_length_max = np.max(np_data[:,0])
print(sepal_length_max)
sepal_width_max = np.max(np_data[:,1])
print(sepal_width_max)
petal_length_max = np.max(np_data[:,2])
print(petal_length_min)
petal_width_max = np.max(np_data[:,3])
print(petal_width_max)

7.9
4.4
1.0
2.5


In [61]:
filter_setosa = np_data[:,-1]==0.0
filter_versicolor = np_data[:,-1]==1.0
filter_virginica = np_data[:,-1]==2.0

print(np.mean(np_data[filter_setosa], axis=0))
print(np.std(np_data[filter_setosa], axis=0))

print(np.mean(np_data[filter_versicolor], axis=0))
print(np.std(np_data[filter_versicolor], axis=0))

print(np.mean(np_data[filter_virginica], axis=0))
print(np.std(np_data[filter_virginica], axis=0))

[5.006 3.418 1.464 0.244 0.   ]
[0.34894699 0.37719491 0.17176728 0.10613199 0.        ]
[5.936 2.77  4.26  1.326 1.   ]
[0.51098337 0.31064449 0.46518813 0.19576517 0.        ]
[6.588 2.974 5.552 2.026 2.   ]
[0.62948868 0.31925538 0.54634787 0.27188968 0.        ]
