### 전국횡단보도표준데이터
    
    1. 횡단보도 연장, 녹생신호시간 : 상관도
    2. 자전거 횡단도 겸용 비율(전체 대비), 
    3. 차로수별 자전거 횡단도 카운트/비율
    4. 차로수별 보행자 신호등 유무 카운트 / 비율
    5. 차로수별 음향신호기설치 유무 카운트 / 비율
    
### 화면 출력
    1. 상관도 수치
    2. 비율 수치
    3. 카운트, 비율
    4. 카운트, 비율
    5. 카운트, 비율
    

In [19]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

np.set_printoptions(precision=5, suppress=True)

def my_split(s):
    block_start = False
    start_index = 0
    ret_list=[]
    for i, c in enumerate(s):
        if block_start==False:
            if c==',':
                ret_list.append(s[start_index:i])
                start_index=i+1
            elif c=='"':
                block_start=True
                start_index = i
        else:
            if c=='"':
                block_start=False
    if s[-1]!=',':
        ret_list.append(s[start_index:])
    return ret_list

def split_len(data_list):
    len_list=[]
    for e in data_list:
        len_list.append(len(e))
    print(set(len_list))
    if len(set(len_list))>1:
        for i in set(len_list):
            print(i, len_list.count(i))
    return set(len_list)

In [71]:
csv_data = []
with open ('전국횡단보도표준데이터.csv') as f:
    for line in f:
        csv_data.append(my_split(line[:-1]))

assert len(split_len(csv_data)) == 1

np_data = np.array(csv_data)
for e in enumerate(np_data[0]):
    print(e)

{28}
(0, '시도명')
(1, '시군구명')
(2, '도로명')
(3, '소재지도로명주소')
(4, '소재지지번주소')
(5, '횡단보도관리번호')
(6, '횡단보도종류')
(7, '자전거횡단도겸용여부')
(8, '고원식적용여부')
(9, '위도')
(10, '경도')
(11, '차로수')
(12, '횡단보도폭')
(13, '횡단보도연장')
(14, '보행자신호등유무')
(15, '보행자작동신호기유무')
(16, '음향신호기설치여부')
(17, '녹색신호시간')
(18, '적색신호시간')
(19, '교통섬유무')
(20, '보도턱낮춤여부')
(21, '점자블록유무')
(22, '집중조명시설유무')
(23, '관리기관명')
(24, '관리기관전화번호')
(25, '데이터기준일자')
(26, '제공기관코드')
(27, '제공기관명')


In [115]:
# 2. 자전거 횡단 겸용비율
sub_data = np.array(np_data[1:,7])
# print(sub_data)
val,cnt = np.unique(sub_data, return_counts=True)
# print(val)
# print(cnt)

filter1 = sub_data != ' '
sub_data_f = sub_data[filter1]
val, cnt = np.unique(sub_data_f, return_counts = True)
# print(val, cnt)
print((cnt * 100) / np.sum(cnt))

[86.46524 13.53476]


In [173]:
# 3. 차로수별 자전거 횡단보도 카운트 / 비율

sub_data = np.array(np_data[1:,[7,11]])
# print(sub_data)

# val,cnt = np.unique(sub_data, return_counts = True)
# print(val)
# print(cnt)

filter1 = (sub_data != ' ') & (sub_data != '0')
sub_data_f = sub_data[filter1]

pass1 = dict()
for yn, road in sub_data_f:
    yr = road.split()[0]
    if yn in pass1.keys():
        pass1[yr].append(yn)
    else:
        pass1[yr] = [yn]
print(pass1)

# pass2 = []
# for road in pass1:
#     val, cnt = np.unique(pass1[road], return_counts=True)
#     y,ratio = 0, 0
#     if 'Y' in val:
#         y = cnt[val == 'Y']
#     ratio = y / np.sum(cnt)
#     pass2.append((int(road), int(y), float(ratio)))
# print(pass2)
# np.set_printoptions(precision=3, suppress=True)

# pass3 = sorted(pass2, key=lambda x : x[0])
# pass3 = np.array(pass3)
# print(pass3)
    
# val, cnt = np.unique(sub_data_f, return_counts = True)
# print(val)
# print(cnt)
# print((cnt * 100) / np.sum(cnt))

ValueError: not enough values to unpack (expected 2, got 1)

In [142]:
# 4. 차로수별 보행자 신호등 유무 카운트/ 비율
sub_data = np.array(np_data[1:,[7,14]])
# print(sub_data)

# val,cnt = np.unique(sub_data, return_counts = True)
# print(val)
# print(cnt)

filter1 = (sub_data != ' ') & (sub_data != '0')
sub_data_f = sub_data[filter1]

val, cnt = np.unique(sub_data_f, return_counts = True)
print(val)
print(cnt)
print((cnt * 100) / np.sum(cnt))

['N' 'Y' 'n' 'y']
[58342 25643    94    11]
[69.38043 30.49471  0.11178  0.01308]


In [141]:
# 5. 차로수별 음향신호기설치 유무 카운트 / 비율
sub_data = np.array(np_data[1:,[7,16]])
# print(sub_data)

# val,cnt = np.unique(sub_data, return_counts = True)
# print(val)
# print(cnt)

filter1 = (sub_data != ' ') & (sub_data != '0')
sub_data_f = sub_data[filter1]

val, cnt = np.unique(sub_data_f, return_counts = True)
print(val)
print(cnt)
print((cnt * 100) / np.sum(cnt))

['N' 'Y' 'n']
[46163  8133   105]
[84.8569  14.95009  0.19301]


In [140]:
# 1.  횡단보도 연장, 녹색신호시간: 상관도
sub_data = np_data[1:,[13,17]]
filter1 = sub_data[:, 1] != ''
sub_data = sub_data[filter1].astype(np.float64)

print(np_mean)
print(np_std)

print(np.corrcoef(sub_data[:,0],sub_data[:,1]))

[13.29805 13.51665]
[26.30099 13.59862]
[[1.      0.18972]
 [0.18972 1.     ]]
