In [1]:
# python list

lista=[]
print(lista)

lista.append('a')
print(lista)


[]
['a']


In [8]:
# numpu ndarray
import numpy as np

array1 = np.array(lista)
array2 = np.array([1,2,3,4])
array3 = np.array([x for x in range(5)])

# array1.a('c')
print(array1, type(array1))
print(array3)

print(array3[[1,4]])
print(array3[array3%2==0])
print(array3[array3>2])

['a'] <class 'numpy.ndarray'>
[0 1 2 3 4]
[1 4]
[0 2 4]
[3 4]


In [13]:
# for, if

# for i in array3:
#     print(i)

for i in range(5):     # np.arange(5)
    if i > 2:
        print(i)

print(array3[array3>2])

3
4
[3 4]


In [34]:
# function

def function_name(n):
    return n*10

return_vlalue = function_name(20)
print('return_vlalue:', return_vlalue)

assert function_name(100) == 1000

return_vlalue: 200


In [36]:
import random

random.seed(88)

listb =[]
for i in range(10):
    listb.append(random.randint(0,100))
print(listb)
    
listc = [random.randint(0,100) for _ in range(10)]
print(listb)
listb_np = [random.randint(0,100) for _ in range(10)]


# lisb에서 50보다 큰값.

listb_np = np.array(listb)
print(listb_np[listb_np>50])
print(len(listb_np[listb_np>50]))

[50, 24, 42, 23, 80, 1, 67, 98, 89, 1]
[50, 24, 42, 23, 80, 1, 67, 98, 89, 1]
[80 67 98 89]
4
